### ISSUE TITLE
Problem when visiting website from a language that is not supported

### ISSUE THREAD

**Issue by JoostvdB94** [thm-projects/arsnova.click-v2#5]
The website becomes unresponsive when visiting arsnova.click from my computer in the Netherlands.
The browsers developer's tools indicate that there was an error when retreiving the nl.json language file.

Perhaps there is a unhandled exception that needs to be catched. I think that English will be a nice deafult language when the users' language is not supported.

I will try to upload some pictures when i'm able to reproduce the issue on my local PC again.

**Comment by trayhem** [comment]
Hi @JoostvdB94,

thanks for the report and the provided details. I was able to confirm this problem.

I've fixed that on our staging server (https://staging.arsnova.click) - feel free to check if it works now (please purge your browser cache to make sure you are on the latest version) and leave a reply here so that we can push it to the production server.

**Comment by JoostvdB94** [comment]
Thanks for the quick fix!
It seems to be working fine now!

(tested in a new private window, site was working fine and saw no errors in the console)

**Comment by trayhem** [comment]
Perfect - thanks for the quick reply. I'll prepare a production release as soon as possible
